### ISSUE TITLE
[Feature request]能否在左侧有个项目结构的树状目录呢？

### ISSUE THREAD

**Issue by fengyingkong** [Tencent/cherry-markdown#366]
**Is your feature request related to a problem? Please describe.**

** What does the proposed API look like**
A clear and concise description of how you propose to solve the problem or provide code samples of how the API would work once implemented.

**Additional context**

**Comment by flgame** [comment]
可以自己把样式覆盖下，比如：
```css
.cherry-previewer {
  width: 100%;
  margin-left: 280px;
  .toc {
    position: absolute;
    left: 0px;
    top: 0px;
    bottom: 0px;
    margin: 0;
    padding: 10px;
    width: 260px;
    overflow: auto;
  }
}
```
